//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotallyNormalCalculator.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TotallyNormalCalculator.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to permanently delete this file?.
        /// </summary>
        public static string blobs_deleteFileQuestion {
            get {
                return ResourceManager.GetString("blobs_deleteFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the files..
        /// </summary>
        public static string blobs_errorOccuredDuringLoading {
            get {
                return ResourceManager.GetString("blobs_errorOccuredDuringLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file type is not supported..
        /// </summary>
        public static string blobs_FileTypeNotSupported {
            get {
                return ResourceManager.GetString("blobs_FileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading files....
        /// </summary>
        public static string blobs_loadingFiles {
            get {
                return ResourceManager.GetString("blobs_loadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no files to delete..
        /// </summary>
        public static string blobs_noBlobsToDelete {
            get {
                return ResourceManager.GetString("blobs_noBlobsToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file to delete..
        /// </summary>
        public static string blobs_selectFileToDelete {
            get {
                return ResourceManager.GetString("blobs_selectFileToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file....
        /// </summary>
        public static string blobs_uploadingFile {
            get {
                return ResourceManager.GetString("blobs_uploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string button_add {
            get {
                return ResourceManager.GetString("button_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string button_delete {
            get {
                return ResourceManager.GetString("button_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string button_update {
            get {
                return ResourceManager.GetString("button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string button_upload {
            get {
                return ResourceManager.GetString("button_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by: Data.
        /// </summary>
        public static string diary_filterby_date {
            get {
                return ResourceManager.GetString("diary_filterby_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by: Message.
        /// </summary>
        public static string diary_filterby_message {
            get {
                return ResourceManager.GetString("diary_filterby_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by: None.
        /// </summary>
        public static string diary_filterby_none {
            get {
                return ResourceManager.GetString("diary_filterby_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by: Title.
        /// </summary>
        public static string diary_filterby_title {
            get {
                return ResourceManager.GetString("diary_filterby_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string diary_placeholder_date {
            get {
                return ResourceManager.GetString("diary_placeholder_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string diary_placeholder_message {
            get {
                return ResourceManager.GetString("diary_placeholder_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string diary_placeholder_title {
            get {
                return ResourceManager.GetString("diary_placeholder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select filter.
        /// </summary>
        public static string diary_selectFilter {
            get {
                return ResourceManager.GetString("diary_selectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string languages_English {
            get {
                return ResourceManager.GetString("languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string languages_French {
            get {
                return ResourceManager.GetString("languages_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string languages_German {
            get {
                return ResourceManager.GetString("languages_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string languages_Greek {
            get {
                return ResourceManager.GetString("languages_Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string languages_Russian {
            get {
                return ResourceManager.GetString("languages_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string languages_Spanish {
            get {
                return ResourceManager.GetString("languages_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string settings_chooseLanguage {
            get {
                return ResourceManager.GetString("settings_chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the app to apply the changes!.
        /// </summary>
        public static string settings_restartApplication {
            get {
                return ResourceManager.GetString("settings_restartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use dark mode.
        /// </summary>
        public static string settings_useDarkMode {
            get {
                return ResourceManager.GetString("settings_useDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string tab_calculator {
            get {
                return ResourceManager.GetString("tab_calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        public static string tab_diary {
            get {
                return ResourceManager.GetString("tab_diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string tab_media {
            get {
                return ResourceManager.GetString("tab_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tab_settings {
            get {
                return ResourceManager.GetString("tab_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string tab_web {
            get {
                return ResourceManager.GetString("tab_web", resourceCulture);
            }
        }
    }
}
